name: 
  en: KPI
  zh: 绩效考核
description:
  en: KPI is a performance evaluation system that allows you to evaluate the performance of your team.
  zh: 绩效考核系统，允许您为团队评估绩效。
tags:
  - 绩效考核
  - KPI
author: DooTask
website: https://www.dootask.com
github: https://github.com/dootask/kpi